const englishConfig = {
   "DECREE_BUTTON": "Make Decree",
   "DAY_BUTTON": "Next Day",
   "DECREE_LIST_TITLE": "Decrees",
   "DAY_TITLE": "Day",
   "INFECTED_TITLE": "Cases",
   "MAX_INFECTED":  500000, 
   "LAST_DAY": 14,
   "ALERT_DECREE_EXISTS": "Decree already exists!",
   "GAME_OVER": "Game Over!",
   "LOST_GAME": "You Lost",
   "WON_GAME": "You Won!",
   "SUB_DECS": {
      "SUB_DECS1": [
           "Avoid",
           "Do not go to",
           "Go to",
           "Do not stay in",
           "Stay in",
           "Will not close",
           "Will close",
      ],
      "SUB_DECS2": [
          "public parks",
          "supermarkets",
          "home",
          "work places",
          "town",
          "walmart",
          "schools",
      ],
      "SUB_DECS3": [
          "for work related reasons",
          "with proper authorization'",
          "in groups of more than two",
          "for health reasons",
          "maintaining a distance of one meter",
          "for manufacturing of strategic interest",
          "for essential work'",
      ],
   },
};
