const francaisConfig = {
   "DECREE_BUTTON": "Créer un décret",
   "DAY_BUTTON": "Jour suivant",
   "DECREE_LIST_TITLE": "Décrets",
   "DAY_TITLE": "Jour",
   "INFECTED_TITLE": "Nombre de cas",
   "MAX_INFECTED":  500000, 
   "LAST_DAY": 14,
   "ALERT_DECREE_EXISTS": "Ce décret existe déja'!",
   "GAME_OVER": "Game Over!",
   "LOST_GAME": "Vous avez perdu",
   "WON_GAME": "Vous avez gagné!",
   "SUB_DECS": {
       "SUB_DECS1": [
           "Entrer",
           "Ne pas aller",
           "Aller",
           "Ne pas rester",
           "Rester",
           "Il est interdit de manger",
           "Il est interdit d'ouvrir la bouche",
       ],
       "SUB_DECS2": [
           "au parc",
           "à l'épicerie",
           "chez vous",
           "au Canadian Tire",
           "au Dollarama",
           "dans un CHSLD",
           "à l'école",
       ],
       "SUB_DECS3": [
           "pour des services essentiels",
           "sans masque",
           "accompagné",
           "en télétravail",
           "'a moins de 2 mètres",
           "si vous êtes âgés de plus de 70 ans",
           "sans désinfectant",
      ],
   },
};